### ISSUE TITLE
Degenotate doesn't run, returning KeyError

### ISSUE THREAD

**Issue by rancilhac** [harvardinformatics/degenotate#23] opened 2023-01-30 11:05 UTC
Hello,

I am trying to run Degenotate to count synonymous and non-synonymous divergence between two species. The program starts running properly and it seems that it can read the annotation file (see the Stdout of my run here: [Degenotate_Stdout.txt](https://github.com/harvardinformatics/degenotate/files/10535172/Degenotate_Stdout.txt)).

However, it crashes when trying to read the exons, and returns this error:

`(degenotate) [los@rackham3 Degenotate]$ more Degenotate.err
Traceback (most recent call last):
  File "/home/los/software/degenotate/degenotate.py", line 59, in <module>
    globs = gxf.read(globs);
  File "/domus/h1/los/software/degenotate/degenotate_lib/gxf.py", line 183, in read
    globs = getLongest(globs);
  File "/domus/h1/los/software/degenotate/degenotate_lib/gxf.py", line 127, in getLongest
    globs['annotation'][longest_transcript]['longest'] = "yes";
KeyError: ''
(degenotate) [los@rackham3 Degenotate]$
`
Any idea where this might come from? I can send more details about my input files if need.

Thanks a lot in advance,

Loïs Rancilhac

**Comment by tsackton** [comment] 2023-01-30 14:49
This is likely arising because there is some feature of your GFF file that degenotate doesn't expect. Can you share your annotation flie, or at least a minimal section of it that reproduces this error? That would help us figure out what is going on.

**Comment by rancilhac** [comment] 2023-01-30 18:50
Thanks a lot for your reply, Tim. You can download the full GFF file here: https://drive.google.com/file/d/1KhP7sgfBffStd_GnY_0OUxH-NQKr9ADB/view?usp=sharing

Cheers,
Loïs

**Comment by tsackton** [comment] 2023-01-30 20:25
The issue is that you have some zero-length transcripts in your GFF file, which are causing issues with the code to detect the longest transcript for a gene (since this code currently assumes that you will have at least one non-zero-length transcript associated with each gene ID).

We are working on a fix that will skip 0 length features and print a warning, which should be pushed in the next day or two (and we will update/close this issue when it is, so you know). In the mean time, if you remove the zero-length features from your GFF, degenotate will hopefully work as is.

**Comment by gwct** [comment] 2023-01-30 20:38
You can view the 0 length features easily with `awk` if you need to:

```bash
awk '{if($4==$5){print}}' [gff file]
```

**Comment by tsackton** [comment] 2023-01-30 21:25
We just pushed a bug fix that will handle 0 length transcripts smoothly. You will need to install degenotate manually (see the instructions in the readme) until this update makes its way to bioconda, which could take a few days.

**Comment by rancilhac** [comment] 2023-02-01 15:30
Thank you so much Gregg & Tim for your quick and helpful replies. I'll try to run Degenotate again with the new version as soon as possible.

**Comment by rancilhac** [comment] 2023-02-02 14:19
Hello,

Degenotate is now running after updating, but I am getting the following error after a couple of transcripts:
`Traceback (most recent call last):
  File "/home/los/software/degenotate/degenotate.py", line 94, in <module>
    globs = degen.processCodons(globs)
  File "/domus/h1/los/software/degenotate/degenotate_lib/degen.py", line 316, in processCodons
    mk_codons = VCF.getVariants(globs, transcript, transcript_region, codons, extra_leading_nt, extra_trailing_nt)
  File "/domus/h1/los/software/degenotate/degenotate_lib/vcf.py", line 238, in getVariants
    max_allele = random.choice(max_allele);
  File "/home/los/.conda/envs/degenotate/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
`
I guess there is a problem with one of the transcripts, but I couldn't trace it in the GFF file. The output files (for the processed transcripts) can be found here: [Degenotate.zip](https://github.com/harvardinformatics/degenotate/files/10569856/Degenotate.zip)

Thanks a lot for your help!

Loïs

**Comment by gwct** [comment] 2023-02-02 15:27
Hi Loïs,
Glad we got past the first issue, so hopefully we can figure this one out too. I think we'll need more information though. I think we would need the sequence and variants for the whole chromosome of the transcript it is failing on (chr1, it looks like) or even the whole genome fasta and vcf if you're able to and that is easier (you can share these by email if preferred).
Basically we need some way to replicate this to figure out what's going on! I'll keep trying to figure it out on my end, but the data would be super helpful!
-Gregg

**Comment by rancilhac** [comment] 2023-02-02 17:33
Thanks a lot, Gregg!
Here are the [reference genome](https://uppsala.box.com/s/yqxepieyth7pxwz08a5kf9d7i9dpissx), the [vcf file ](https://uppsala.box.com/s/tkw33dcyrlfvvjmtqonyuou399znairk) and the [vcf tabix index](https://uppsala.box.com/s/0p1a0ei6wmfuyrijdrfii0fbcyoi0ha0) if needed. Also text files with [outgroup samples](https://uppsala.box.com/s/tb1hofwmmte7k5cmwj9bwzwpu8bmn9f9) and [samples to exclude](https://uppsala.box.com/s/mxiq49loiu4dzsdbrybnp3cyuj9m010r).

I ran Degenotate as follow: `python /home/los/software/degenotate/degenotate.py -a $WORKDIR/Motacilla_alba_V1.0_no_HiC_scaffolds.gff -g $REF -v $VCF -u Outgroups.txt -e bocagii_samples.txt -o $WORKDIR/Degenotate_bocagii2 --overwrite`

Best,
Loïs

**Comment by gwct** [comment] 2023-02-02 22:05
Hello again,

I think I figured out the cause of this problem. It turns out there is at least one site (possibly more, I didn't check) in your VCF that has an alternate allele, but that allele does not exist in any of the samples:

```
chr1   115796  .       T       C       6572.15 PASS    .       GT      ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     0|0     ./.     ./.     ./.     ./.     ./.     0|0     ./.     0|0     ./.     ./.     ./.
```

This caused the program to crash because it was still looking for an alternate allele among the outgroup species. I'm not sure why there would be an alternate allele reported here but not present in any of the samples. Was this VCF subsampled?

We've pushed fixes for this on our end though. Sites like this will now be skipped. You should be able to pull the changes directly from github now, or update the bioconda package sometime in the next couple of days. 
Let us know if you have any more problems!

**Comment by gwct** [comment] 2023-02-03 14:57
The new version that incorporates these fixes is now available on bioconda, so if that's how you have it installed you should be able to `conda update degenotate` and try it out. Feel free to start a new issue if you run into anything else!

**Closed by gwct** 2023-02-03 14:57 UTC

**Comment by rancilhac** [comment] 2023-02-03 16:30
Thanks again for your help! Degenotate ran fine. I encountered another error because I had genes of length=1bp, which caused Degenotate to crash. I solved the issue by removing these features from the gff file, but I thought it might be useful for you to know.

I also have a question regarding the dN/dS calculation: I read in the l manual page that sites that are fixed for the alternative allele in the ingroup will be counted as polymorphisms. This is an issue for me because my reference genome is from a different species as my ingroup, and I expect most fixed differences in my ingroup to be homozygous alternate. Any idea whether I could find a way around this issue, or if I should use a different tool than Degenotate?

Cheers,
Loïs

**Comment by tsackton** [comment] 2023-02-03 17:32
Hi Loïs,

In your case, is the reference genome your outgroup species? Or do you have reference, ingroup, and outgroup as three separate species? 

We are working on a way to support the case where the reference genome is the outgroup, although it is not totally straightforward because it changes the logic of how we compute fixed differences (e.g., in this case, position where the ingroup are fixed for the alternate allele is actually a fixed difference, not a site to skip). 

The case where both ingroup and outgroup species are separate from the reference is quite tricky and probably not something we will support. In this case, doing something like making a pseudo-reference for either the ingroup (preferable) or the outgroup (if necessary) using a tool like [pseudo-it](https://github.com/goodest-goodlab/pseudo-it) and then regenerating your vcfs may be your best option. 

Tim

**Comment by rancilhac** [comment] 2023-02-06 09:32
Hi Tim,
Yes, my reference is also my outgroup. In case you implement this in Degenotate, I'd be very keen on trying it.
Cheers,
Loïs
